apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: order-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service-container
        image: himanshuuppal/order-service:assignment2
        env:
        - name: JAEGER_COLLECTOR_URL
          value: jaeger-collector.default.svc.cluster.local      
        ports:
        - containerPort: 9000 